site_name: Grim Docs

nav:
    - Home: 'index.md'
    - How to Edit an Item: import-single-record.md
    - Hard Modding Method: van-hard-modding.md
    - Base Game Tools:
        - 'Modding Tools': mod-tools.md
    - 'About': 'about.md'

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/sword
    repo: material/github
    edit: material/pencil-plus
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.share
    - navigation.footer
    - content.action.edit
  custom_dir: overrides

repo_url: https://github.com/AirTechWick/grim-docs    
repo_name: AirTechWick/grim-docs
edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - md_in_html