site_name: Grim Docs

nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Modding Setup: 
      - Setup Guide 1: 'setup1.md'
      - Setup Guide 2: 'setup2.md'
    - Editing a Base Game Item: import-single-record.md
    - Edit NPCs Name: 
      - powbam Edit NPC Name: powbam-edit-name.md
      - Denis Edit Name Lite: denis-edit-name.md
    - Hard Modding: 
      - VanH Hard Mod Tutorial: van-hard-mod.md
      - tqFan Hard Mod Tutorial: tqfan-hard-mod.md
    - PSEditor :
      - PSEditor Tutorial: pseditor.md
      - Emission Pattern Tutorial: emission-pattern.md
    - Mods on Steamdeck: steam-deck-mods.md
    - Modpacks: modpacks.md
    - Official PDF Guide: crate-pdf-guide.md
    - Add Page [ + ]: template-page.md

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/sword
    repo: material/github
    edit: material/pencil-plus
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.share
    - navigation.footer
    - content.action.edit
    - content.code.copy
  custom_dir: overrides

repo_url: https://github.com/AirTechWick/grim-docs    
repo_name: AirTechWick/grim-docs
edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - glightbox
  - search
  