site_name: Grim Docs
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/sword
  features:
    - navigation.tracking
    - navigation.expand